FROM golang:1.22-alpine AS builder
RUN apk add --no-cache ca-certificates git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/service ./cmd/ingestor

FROM alpine:3.20
RUN apk add --no-cache ca-certificates wget
COPY --from=builder /bin/service /bin/service
ENTRYPOINT ["/bin/service"]
