apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: dashboard
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
  - target:
      kind: Service
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
